// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdS7uYwom9FLeOexCWgpX1Vru0T8jO4f0',
    appId: '1:634926542931:web:c3bcc393e1293198e896a6',
    messagingSenderId: '634926542931',
    projectId: 'school-taxi-ae8b1',
    authDomain: 'school-taxi-ae8b1.firebaseapp.com',
    storageBucket: 'school-taxi-ae8b1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnPE9kpwI6v1KnDaZCBvLs6XYsMPFJKaY',
    appId: '1:634926542931:android:66dd8bce058903f7e896a6',
    messagingSenderId: '634926542931',
    projectId: 'school-taxi-ae8b1',
    storageBucket: 'school-taxi-ae8b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqg6dI8zdICCU1RKkKjZjoWE1ZcN33YtA',
    appId: '1:634926542931:ios:bbe484dde470422de896a6',
    messagingSenderId: '634926542931',
    projectId: 'school-taxi-ae8b1',
    storageBucket: 'school-taxi-ae8b1.firebasestorage.app',
    iosBundleId: 'com.example.schoolTaxi',
  );
}
